# Generated by Django 4.1.3 on 2022-12-12 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='student_class',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='student_class',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_class',
            new_name='class_id',
        ),
    ]
