# Generated by Django 4.1.3 on 2022-12-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(to='apis.group'),
        ),
    ]
